// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewUserWrite struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUserWrite) Reset()         { *m = NewUserWrite{} }
func (m *NewUserWrite) String() string { return proto.CompactTextString(m) }
func (*NewUserWrite) ProtoMessage()    {}
func (*NewUserWrite) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{0}
}

func (m *NewUserWrite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserWrite.Unmarshal(m, b)
}
func (m *NewUserWrite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserWrite.Marshal(b, m, deterministic)
}
func (m *NewUserWrite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserWrite.Merge(m, src)
}
func (m *NewUserWrite) XXX_Size() int {
	return xxx_messageInfo_NewUserWrite.Size(m)
}
func (m *NewUserWrite) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserWrite.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserWrite proto.InternalMessageInfo

func (m *NewUserWrite) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NewUserWrite) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type NewUserRead struct {
	Successfully         bool     `protobuf:"varint,1,opt,name=successfully,proto3" json:"successfully,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUserRead) Reset()         { *m = NewUserRead{} }
func (m *NewUserRead) String() string { return proto.CompactTextString(m) }
func (*NewUserRead) ProtoMessage()    {}
func (*NewUserRead) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{1}
}

func (m *NewUserRead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserRead.Unmarshal(m, b)
}
func (m *NewUserRead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserRead.Marshal(b, m, deterministic)
}
func (m *NewUserRead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserRead.Merge(m, src)
}
func (m *NewUserRead) XXX_Size() int {
	return xxx_messageInfo_NewUserRead.Size(m)
}
func (m *NewUserRead) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserRead.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserRead proto.InternalMessageInfo

func (m *NewUserRead) GetSuccessfully() bool {
	if m != nil {
		return m.Successfully
	}
	return false
}

type QuestionWrite struct {
	ChatId               int64    `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuestionWrite) Reset()         { *m = QuestionWrite{} }
func (m *QuestionWrite) String() string { return proto.CompactTextString(m) }
func (*QuestionWrite) ProtoMessage()    {}
func (*QuestionWrite) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{2}
}

func (m *QuestionWrite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuestionWrite.Unmarshal(m, b)
}
func (m *QuestionWrite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuestionWrite.Marshal(b, m, deterministic)
}
func (m *QuestionWrite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuestionWrite.Merge(m, src)
}
func (m *QuestionWrite) XXX_Size() int {
	return xxx_messageInfo_QuestionWrite.Size(m)
}
func (m *QuestionWrite) XXX_DiscardUnknown() {
	xxx_messageInfo_QuestionWrite.DiscardUnknown(m)
}

var xxx_messageInfo_QuestionWrite proto.InternalMessageInfo

func (m *QuestionWrite) GetChatId() int64 {
	if m != nil {
		return m.ChatId
	}
	return 0
}

type QuestionRead struct {
	Successfully         bool     `protobuf:"varint,1,opt,name=successfully,proto3" json:"successfully,omitempty"`
	ChatId               int64    `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Question             string   `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuestionRead) Reset()         { *m = QuestionRead{} }
func (m *QuestionRead) String() string { return proto.CompactTextString(m) }
func (*QuestionRead) ProtoMessage()    {}
func (*QuestionRead) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{3}
}

func (m *QuestionRead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuestionRead.Unmarshal(m, b)
}
func (m *QuestionRead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuestionRead.Marshal(b, m, deterministic)
}
func (m *QuestionRead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuestionRead.Merge(m, src)
}
func (m *QuestionRead) XXX_Size() int {
	return xxx_messageInfo_QuestionRead.Size(m)
}
func (m *QuestionRead) XXX_DiscardUnknown() {
	xxx_messageInfo_QuestionRead.DiscardUnknown(m)
}

var xxx_messageInfo_QuestionRead proto.InternalMessageInfo

func (m *QuestionRead) GetSuccessfully() bool {
	if m != nil {
		return m.Successfully
	}
	return false
}

func (m *QuestionRead) GetChatId() int64 {
	if m != nil {
		return m.ChatId
	}
	return 0
}

func (m *QuestionRead) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

type AnswerWrite struct {
	ChatId               int64    `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Answer               string   `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnswerWrite) Reset()         { *m = AnswerWrite{} }
func (m *AnswerWrite) String() string { return proto.CompactTextString(m) }
func (*AnswerWrite) ProtoMessage()    {}
func (*AnswerWrite) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{4}
}

func (m *AnswerWrite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnswerWrite.Unmarshal(m, b)
}
func (m *AnswerWrite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnswerWrite.Marshal(b, m, deterministic)
}
func (m *AnswerWrite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnswerWrite.Merge(m, src)
}
func (m *AnswerWrite) XXX_Size() int {
	return xxx_messageInfo_AnswerWrite.Size(m)
}
func (m *AnswerWrite) XXX_DiscardUnknown() {
	xxx_messageInfo_AnswerWrite.DiscardUnknown(m)
}

var xxx_messageInfo_AnswerWrite proto.InternalMessageInfo

func (m *AnswerWrite) GetChatId() int64 {
	if m != nil {
		return m.ChatId
	}
	return 0
}

func (m *AnswerWrite) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

type AnswerRead struct {
	Successfully         bool     `protobuf:"varint,1,opt,name=successfully,proto3" json:"successfully,omitempty"`
	ChatId               int64    `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Correct              bool     `protobuf:"varint,3,opt,name=correct,proto3" json:"correct,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnswerRead) Reset()         { *m = AnswerRead{} }
func (m *AnswerRead) String() string { return proto.CompactTextString(m) }
func (*AnswerRead) ProtoMessage()    {}
func (*AnswerRead) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{5}
}

func (m *AnswerRead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnswerRead.Unmarshal(m, b)
}
func (m *AnswerRead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnswerRead.Marshal(b, m, deterministic)
}
func (m *AnswerRead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnswerRead.Merge(m, src)
}
func (m *AnswerRead) XXX_Size() int {
	return xxx_messageInfo_AnswerRead.Size(m)
}
func (m *AnswerRead) XXX_DiscardUnknown() {
	xxx_messageInfo_AnswerRead.DiscardUnknown(m)
}

var xxx_messageInfo_AnswerRead proto.InternalMessageInfo

func (m *AnswerRead) GetSuccessfully() bool {
	if m != nil {
		return m.Successfully
	}
	return false
}

func (m *AnswerRead) GetChatId() int64 {
	if m != nil {
		return m.ChatId
	}
	return 0
}

func (m *AnswerRead) GetCorrect() bool {
	if m != nil {
		return m.Correct
	}
	return false
}

type LeaderboardWrite struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaderboardWrite) Reset()         { *m = LeaderboardWrite{} }
func (m *LeaderboardWrite) String() string { return proto.CompactTextString(m) }
func (*LeaderboardWrite) ProtoMessage()    {}
func (*LeaderboardWrite) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{6}
}

func (m *LeaderboardWrite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaderboardWrite.Unmarshal(m, b)
}
func (m *LeaderboardWrite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaderboardWrite.Marshal(b, m, deterministic)
}
func (m *LeaderboardWrite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaderboardWrite.Merge(m, src)
}
func (m *LeaderboardWrite) XXX_Size() int {
	return xxx_messageInfo_LeaderboardWrite.Size(m)
}
func (m *LeaderboardWrite) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaderboardWrite.DiscardUnknown(m)
}

var xxx_messageInfo_LeaderboardWrite proto.InternalMessageInfo

type Leader struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Cnt                  int32    `protobuf:"varint,2,opt,name=cnt,proto3" json:"cnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Leader) Reset()         { *m = Leader{} }
func (m *Leader) String() string { return proto.CompactTextString(m) }
func (*Leader) ProtoMessage()    {}
func (*Leader) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{7}
}

func (m *Leader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Leader.Unmarshal(m, b)
}
func (m *Leader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Leader.Marshal(b, m, deterministic)
}
func (m *Leader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Leader.Merge(m, src)
}
func (m *Leader) XXX_Size() int {
	return xxx_messageInfo_Leader.Size(m)
}
func (m *Leader) XXX_DiscardUnknown() {
	xxx_messageInfo_Leader.DiscardUnknown(m)
}

var xxx_messageInfo_Leader proto.InternalMessageInfo

func (m *Leader) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Leader) GetCnt() int32 {
	if m != nil {
		return m.Cnt
	}
	return 0
}

type LeaderboardRead struct {
	Successfully         bool      `protobuf:"varint,1,opt,name=successfully,proto3" json:"successfully,omitempty"`
	Leaders              []*Leader `protobuf:"bytes,2,rep,name=leaders,proto3" json:"leaders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LeaderboardRead) Reset()         { *m = LeaderboardRead{} }
func (m *LeaderboardRead) String() string { return proto.CompactTextString(m) }
func (*LeaderboardRead) ProtoMessage()    {}
func (*LeaderboardRead) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{8}
}

func (m *LeaderboardRead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaderboardRead.Unmarshal(m, b)
}
func (m *LeaderboardRead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaderboardRead.Marshal(b, m, deterministic)
}
func (m *LeaderboardRead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaderboardRead.Merge(m, src)
}
func (m *LeaderboardRead) XXX_Size() int {
	return xxx_messageInfo_LeaderboardRead.Size(m)
}
func (m *LeaderboardRead) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaderboardRead.DiscardUnknown(m)
}

var xxx_messageInfo_LeaderboardRead proto.InternalMessageInfo

func (m *LeaderboardRead) GetSuccessfully() bool {
	if m != nil {
		return m.Successfully
	}
	return false
}

func (m *LeaderboardRead) GetLeaders() []*Leader {
	if m != nil {
		return m.Leaders
	}
	return nil
}

func init() {
	proto.RegisterType((*NewUserWrite)(nil), "api.NewUserWrite")
	proto.RegisterType((*NewUserRead)(nil), "api.NewUserRead")
	proto.RegisterType((*QuestionWrite)(nil), "api.QuestionWrite")
	proto.RegisterType((*QuestionRead)(nil), "api.QuestionRead")
	proto.RegisterType((*AnswerWrite)(nil), "api.AnswerWrite")
	proto.RegisterType((*AnswerRead)(nil), "api.AnswerRead")
	proto.RegisterType((*LeaderboardWrite)(nil), "api.LeaderboardWrite")
	proto.RegisterType((*Leader)(nil), "api.Leader")
	proto.RegisterType((*LeaderboardRead)(nil), "api.LeaderboardRead")
}

func init() { proto.RegisterFile("api/api.proto", fileDescriptor_1b40cafcd4234784) }

var fileDescriptor_1b40cafcd4234784 = []byte{
	// 482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x51, 0x8b, 0xd3, 0x40,
	0x10, 0xc7, 0x69, 0x82, 0x69, 0x9d, 0xf4, 0xae, 0xed, 0xa0, 0x77, 0x21, 0xea, 0x51, 0x56, 0x94,
	0x3e, 0xdd, 0x62, 0x05, 0x1f, 0x7c, 0x10, 0xee, 0x5e, 0x0e, 0x41, 0x44, 0xa3, 0xde, 0x81, 0x08,
	0xb2, 0x4d, 0xd6, 0xba, 0x50, 0xb3, 0x31, 0xbb, 0xe5, 0x90, 0xd2, 0x17, 0xbf, 0x82, 0x1f, 0xcd,
	0xaf, 0x20, 0xf8, 0x35, 0x24, 0xbb, 0x49, 0xba, 0x11, 0x84, 0x82, 0x6f, 0x99, 0xc9, 0xce, 0x6f,
	0xfe, 0x3b, 0xf3, 0x5f, 0x38, 0x60, 0x85, 0xa0, 0xac, 0x10, 0xa7, 0x45, 0x29, 0xb5, 0x44, 0x9f,
	0x15, 0x22, 0xbe, 0xbb, 0x94, 0x72, 0xb9, 0xe2, 0xd4, 0xfc, 0xca, 0x73, 0xa9, 0x99, 0x16, 0x32,
	0x57, 0xf6, 0x08, 0x79, 0x0a, 0xc3, 0x97, 0xfc, 0xfa, 0x9d, 0xe2, 0xe5, 0x55, 0x29, 0x34, 0xc7,
	0x43, 0xf0, 0x44, 0x16, 0xf5, 0xa6, 0xbd, 0x99, 0x9f, 0x78, 0x22, 0xc3, 0x18, 0x06, 0x6b, 0xc5,
	0xcb, 0x9c, 0x7d, 0xe1, 0x91, 0x37, 0xed, 0xcd, 0x6e, 0x26, 0x6d, 0x4c, 0x1e, 0x41, 0x58, 0xd7,
	0x26, 0x9c, 0x65, 0x48, 0x60, 0xa8, 0xd6, 0x69, 0xca, 0x95, 0xfa, 0xb4, 0x5e, 0xad, 0xbe, 0x19,
	0xc8, 0x20, 0xe9, 0xe4, 0xc8, 0x0c, 0x0e, 0x5e, 0xaf, 0xb9, 0xaa, 0x14, 0xd8, 0x7e, 0xc7, 0xd0,
	0x4f, 0x3f, 0x33, 0xfd, 0xb1, 0x6d, 0x1a, 0x54, 0xe1, 0xf3, 0x8c, 0x2c, 0x61, 0xd8, 0x9c, 0xdc,
	0x97, 0xee, 0xc2, 0x3c, 0x17, 0x56, 0xdd, 0xe2, 0x6b, 0x0d, 0x8b, 0x7c, 0x7b, 0x8b, 0x26, 0x26,
	0xcf, 0x20, 0x3c, 0xcb, 0xd5, 0x75, 0x33, 0x80, 0x7f, 0x09, 0xc2, 0x23, 0x08, 0x98, 0x39, 0x57,
	0xcf, 0xa1, 0x8e, 0x48, 0x0a, 0x60, 0xeb, 0xff, 0x5f, 0x66, 0x04, 0xfd, 0x54, 0x96, 0x25, 0x4f,
	0xb5, 0x51, 0x39, 0x48, 0x9a, 0x90, 0x20, 0x8c, 0x5f, 0x70, 0x96, 0xf1, 0x72, 0x21, 0x59, 0x99,
	0x19, 0xa5, 0xe4, 0x09, 0x04, 0x36, 0xd7, 0x59, 0x52, 0xaf, 0xbb, 0x24, 0x1c, 0x83, 0x9f, 0xe6,
	0xda, 0x34, 0xba, 0x91, 0x54, 0x9f, 0xe4, 0x03, 0x8c, 0x1c, 0xd6, 0xde, 0xaa, 0x1f, 0x40, 0x7f,
	0x65, 0xca, 0x54, 0xe4, 0x4d, 0xfd, 0x59, 0x38, 0x0f, 0x4f, 0x2b, 0xa7, 0x59, 0x54, 0xd2, 0xfc,
	0x9b, 0xff, 0xf6, 0x20, 0x38, 0x97, 0xfa, 0xac, 0x10, 0x78, 0x09, 0xf0, 0x86, 0xeb, 0xda, 0x22,
	0x38, 0x31, 0xc7, 0x5d, 0xb3, 0xc5, 0x63, 0x37, 0x55, 0x09, 0x21, 0xf7, 0xbf, 0xff, 0xfc, 0xf5,
	0xc3, 0xbb, 0x87, 0x77, 0xa8, 0x6a, 0x2b, 0xe9, 0x46, 0x64, 0x5b, 0xba, 0x69, 0x6e, 0xb4, 0xc5,
	0xb7, 0x10, 0x5e, 0x70, 0xdd, 0xb8, 0x03, 0xd1, 0x50, 0x3a, 0xb6, 0x8a, 0x27, 0x9d, 0x9c, 0x41,
	0x9f, 0x18, 0x74, 0x84, 0x47, 0x74, 0xb9, 0x2b, 0xa6, 0x9b, 0x7a, 0x13, 0x5b, 0xbc, 0x02, 0x78,
	0x25, 0x95, 0xb6, 0xbb, 0x44, 0x2b, 0xcd, 0x31, 0x46, 0x3c, 0x72, 0x32, 0x06, 0xf8, 0xd0, 0x00,
	0xa7, 0x78, 0x42, 0x8b, 0xb6, 0x6e, 0xc7, 0xa3, 0x1b, 0xeb, 0x8f, 0x2d, 0x5e, 0xc2, 0xe1, 0x05,
	0xd7, 0xce, 0xc8, 0xf1, 0xb6, 0x33, 0xb9, 0xdd, 0x42, 0xe3, 0x5b, 0x7f, 0xa7, 0x4d, 0x9b, 0x63,
	0xd3, 0x66, 0x42, 0x46, 0xb4, 0x4b, 0x39, 0x87, 0xf7, 0x83, 0xf9, 0x42, 0xea, 0xea, 0x61, 0x2f,
	0x02, 0xf3, 0x9a, 0x1f, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x70, 0x8a, 0xce, 0x0a, 0x01, 0x04,
	0x00, 0x00,
}
